In [68]:
import numpy as np
import pandas as pd
from datetime import datetime

In [95]:
df = pd.read_csv('../datasets/Corona_NLP_train.csv')
df = df[['TweetAt' , 'OriginalTweet' , 'Sentiment']]
df['TweetAt'] = pd.to_datetime(df['TweetAt'], format='%d-%m-%Y' ,  errors='coerce')
df

/home/younes/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (15,16) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,TweetAt,OriginalTweet,Sentiment
0,2020-03-16,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,2020-03-16,advice Talk to your neighbours family to excha...,Positive
2,2020-03-16,Coronavirus Australia: Woolworths to give elde...,Positive
3,2020-03-16,My food stock is not the only one which is emp...,Positive
4,2020-03-16,"Me, ready to go at supermarket during the #COV...",Extremely Negative
...,...,...,...
41151,2020-04-14,Airline pilots offering to stock supermarket s...,Neutral
41152,2020-04-14,Response to complaint not provided citing COVI...,Extremely Negative
41153,2020-04-14,You know its getting tough when @KameronWilds...,Positive
41154,2020-04-14,Is it wrong that the smell of hand sanitizer i...,Neutral
41155,2020-04-14,@TartiiCat Well new/used Rift S are going for ...,Negative

In [96]:
df['WeekDay'] = df['TweetAt'].dt.day_name()
df

,TweetAt,OriginalTweet,Sentiment,WeekDay
0,2020-03-16,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral,Monday
1,2020-03-16,advice Talk to your neighbours family to excha...,Positive,Monday
2,2020-03-16,Coronavirus Australia: Woolworths to give elde...,Positive,Monday
3,2020-03-16,My food stock is not the only one which is emp...,Positive,Monday
4,2020-03-16,"Me, ready to go at supermarket during the #COV...",Extremely Negative,Monday
...,...,...,...,...
41151,2020-04-14,Airline pilots offering to stock supermarket s...,Neutral,Tuesday
41152,2020-04-14,Response to complaint not provided citing COVI...,Extremely Negative,Tuesday
41153,2020-04-14,You know its getting tough when @KameronWilds...,Positive,Tuesday
41154,2020-04-14,Is it wrong that the smell of hand sanitizer i...,Neutral,Tuesday
41155,2020-04-14,@TartiiCat Well new/used Rift S are going for ...,Negative,Tuesday

In [97]:
df.isnull().sum()

TweetAt          17
OriginalTweet     0
Sentiment         0
WeekDay          17
dtype: int64

In [98]:
df=df.dropna(axis=0)

In [99]:
df = pd.get_dummies(df, columns = ['WeekDay'])

In [100]:
df = df.drop(['TweetAt'], axis=1)

In [101]:
df

,OriginalTweet,Sentiment,WeekDay_Friday,WeekDay_Monday,WeekDay_Saturday,WeekDay_Sunday,WeekDay_Thursday,WeekDay_Tuesday,WeekDay_Wednesday
0,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral,0,1,0,0,0,0,0
1,advice Talk to your neighbours family to excha...,Positive,0,1,0,0,0,0,0
2,Coronavirus Australia: Woolworths to give elde...,Positive,0,1,0,0,0,0,0
3,My food stock is not the only one which is emp...,Positive,0,1,0,0,0,0,0
4,"Me, ready to go at supermarket during the #COV...",Extremely Negative,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
41151,Airline pilots offering to stock supermarket s...,Neutral,0,0,0,0,0,1,0
41152,Response to complaint not provided citing COVI...,Extremely Negative,0,0,0,0,0,1,0
41153,You know its getting tough when @KameronWilds...,Positive,0,0,0,0,0,1,0
41154,Is it wrong that the smell of hand sanitizer i...,Neutral,0,0,0,0,0,1,0
41155,@TartiiCat Well new/used Rift S are going for ...,Negative,0,0,0,0,0,1,0